### ISSUE TITLE
doesn't redirect after login on localhost

### ISSUE THREAD

**Issue by kylec** [nov/fb_graph_sample#10]
Thanks for writing this wonderful sample app to showcase the cool features of fb_graph. I have a question regarding authentication on local host. I cloned your sample app and changed client id and secret in facebook.yml to my own test app's. After I clicked on login. I get a popup to type in my facebook username and password but it doesn't redirect.  However, it works on heroku , just not on localhost.

I've edited the url on facebook developler site to point to my localhost but that doesnt' solve the problem.

Your help is much appreciated.

**Comment by nov** [comment]
Humm, can you try pow?
My client_id embedded in facebook.yml is setup for "fb-graph.dev" domain.

Since I'm not using "localhost" for a long time, I don't know facebook still allows "localhost".
But in general, using "localhost" or "120.0.0.1" as OAuth client domain is troublesome.

**Comment by denishaskin** [comment]
Here's what I did to be able to run this locally.  Not sure if _all_ steps are required, but:
1. add an entry into my local /etc/hosts mapping fb-graph-sample.dev to localhost: "127.0.0.1 fb-graph-sample.dev"
2. Went to facebook and created a new app.  Made App Domains=fb-graph-sample.dev and made the Website with Facebook Login Site URL be "fb-graph-sample.dev"
3. Once the app was created, noted the "App Id" and "App Secret" of the facebook app.
4. edited config/facebook.yml and inserted the previous two values in for client_id and client_secret.
5. rake db:migrate to make sure tables were created
6. rails s
7. point browser to http://fb-graph-sample.dev:3000
8. clicked Log In over in the right sidebar, logged into Facebook, said yes to the permission questions
9. Was able to see my profile, feed, etc

**Comment by nov** [comment]
Thanks for your sharing.

Maybe you can use my FB app's credentials for "fb-graph-sample.dev" domain.
Other than that, what you did is all what you need to do, I think.

**Comment by denishaskin** [comment]
No, I had tried that.  Didn't work.

**Comment by nov** [comment]
Opps, sorry.
I've changed the app domain to 'http://fb-graph.dev/'.
