### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by daroay** [nov/fb_graph_sample#2]
For some reason it keep saying to me  "facebook cookie not found"

**Comment by daroay** [comment]
Oh, of course, my apps url was not localhost:3000 duh!

**Comment by nov** [comment]
Is facebook cookie there? or missing?
When you logged in using facebook's JavaScript SDK, you should have a cookie which named as fb_\* and includes an access_token in it.

**Comment by nov** [comment]
more details about the cookie here.
http://developers.facebook.com/docs/authentication/#single-sign-on-with-the-javascript-sdk

**Comment by daroay** [comment]
I got it solved now, Thanks!

**Comment by nov** [comment]
Cool ;)
