### ISSUE TITLE
API Error Code: 191 for Canvas application 

### ISSUE THREAD

**Issue by ghost** [nov/fb_graph_sample#5]
When I tried using this example for Canvas application, It gives me the error: 

API Error Code: 191
API Error Description: The specified URL is not owned by the application
Error Message: Invalid redirect_uri: Given URL is not allowed by the Application configuration.

This works perfectly using login button in the home page, But not in the Canvas.

**Comment by ghost** [comment]
After some Googling and debugging, I solved by putting a small fix  in the authorize.html.erb in the canvas Folder in the views.

<script>
  top.location.href = '<%= @auth.authorize_uri(canvas_url).html_safe+"%2F" %>';
</script>


Seems to be the problem related with backslash. Just wanted to bring this to notice.

**Comment by nov** [comment]
I recommend you to put "/" in facebook.yml (or ENV['fb_canvas_url'] if using Heroku) not in the view.

**Comment by devudilip** [comment]
Hi

even m getting the same error, it was working fine till last month,
allof sudden i m getting this error.
i am following your app only,
with customised facebook.yml

my app name is: sampleapp
domain is : localhost
website: http://localhost:300/

is there any extra procedure to create app in facebook?
is this problem from fb app side ?
