### ISSUE TITLE
Problem for to ask permission on tab page application

### ISSUE THREAD

**Issue by maxiperezunlam** [nov/fb_graph_sample#6]
I am making  a tab application on facebook. So i need ask permission when the user click in like button. Ok, when the user click in like button redirect via AJAX to ask_permission action.

--------------------------------------action----------------------------------------
def ask_permission
## end

-------------------------------------view ask_permission.js.erb--------------
window.location.href = '<%=  @auth.client.authorization_uri(
                      :scope => [:email, :read_stream, :offline_access, :manage_pages, :user_about_me]
##                   ) %>';

So in the view i try redirect with jQuery to authorization url however throw this message:

{
   "error": {
      "message": "Missing redirect_uri parameter.",
      "type": "OAuthException"
   }
}

NOTE: currently my redirect_uri is localhost:3000. 

Which could be the problem?

**Comment by nov** [comment]
What's the actual output of <code>@auth.client.authorization_uri(:scope => ...)</code>?
Does it have <code>redirect_uri</code> in its query?

**Comment by maxiperezunlam** [comment]
Excuse me the generated url is https://graph.facebook.com/oauth/authorize?client_id=XXXXXXXXXXXX&redirect_uri=http%3A%2F%2Ffbpromo.testenvironment.com.ar%2Fauthorize&response_type=code&scope=email+read_stream+offline_access+manage_pages+user_about_me

**Comment by maxiperezunlam** [comment]
Excuse me again the problem was my configuration. However how I could config my application for ask permission in tab page and the redirect into tab application.

Example go to tab application A, Ask permissions and then facebook redirect into tab application A.

Thanks in advance

**Comment by nov** [comment]
Sorry, I'm not familiar with page tabs.
However, I think you can change your redirect_uri to your tab app URL and let users redirect to the canvas page after authenticated.
