### ISSUE TITLE
necessary changes to be made for this app to be running in devlopment

### ISSUE THREAD

**Issue by ckgagan** [nov/fb_graph_sample#7]
Can any one please kindly show what are the necessary changes to be made in this app so that it works in development. Like where to put access token, app_id etc and where to find these values in Facebook.

Thanks

**Comment by nov** [comment]
My FB app id&secret is set to work for "fb-graph-sample.dev" domain.
You can use the domain using pow, or modify config/facebook.yml for your development env (localhost:3000, I guess).

**Comment by nov** [comment]
I'll explain how to do it in README soon.
Thanks
https://github.com/nov/fb_graph_sample/issues/8

**Comment by ckgagan** [comment]
Hey NOV I guess the README is not updated till now.
I am waiting for it :)

**Comment by nov** [comment]
I moved sample code to github wiki.

**Comment by ckgagan** [comment]
I am unable to find the link. Can you please post the link :)
